version: 0.2
phases:
  install:
    commands:
      - mv /usr/local/bin/docker /usr/bin/docker
      - curl -L https://raw.githubusercontent.com/docker/compose-cli/main/scripts/install/install_linux.sh | sh
  pre_build:
    commands:
      - curl "http://${IPV4_PORT}${AWS_CONTAINER_CREDENTIALS_RELATIVE_URI}" > creds.json
      - export AWS_ACCESS_KEY_ID=$(cat creds.json | jq -r .AccessKeyId)
      - export AWS_SECRET_ACCESS_KEY=$(cat creds.json | jq -r .SecretAccessKey)
      - export AWS_SESSION_TOKEN=$(cat creds.json | jq -r .Token)
      - bash ./scripts/docker-login.sh
      - docker context create ecs ecs --from-env
      - docker context use ecs
  build:
    commands:
      - docker compose -f compose.yml -f compose.prod.yml up
