version: '3.9'
services:
  backend:
    build:
      context: ./packages/backend
      dockerfile: Dockerfile.dev
    depends_on:
      - db
    environment:
      DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE}
      BACKEND_SECRET_KEY: ${BACKEND_SECRET_KEY}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}

  frontend:
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: ${NODE_ENV}
    depends_on:
      - backend

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
