version: "3.9"
services:

  backend:
    build:
      context: ./packages/backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./packages/backend:/app/backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    stdin_open: true
    tty: true
    depends_on:
      - db
    environment:
      DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}

  frontend:
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./packages/frontend:/app
      # One-way volume to use node_modules from inside image
      - /app/node_modules
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    environment:
      NODE_ENV: ${NODE_ENV}
    depends_on:
      - backend
    command: yarn start

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - /tmp/postgres-data:/var/lib/postgresql/data

