version: '3.9'
services:
  backend:
    build: ./packages/backend
    depends_on:
      - db
    environment:
      DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE}
      BACKEND_SECRET_KEY: ${BACKEND_SECRET_KEY}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      UWSGI_WSGI_FILE: ${UWSGI_WSGI_FILE}
      UWSGI_WORKERS: ${UWSGI_WORKERS}
      UWSGI_THREADS: ${UWSGI_THREADS}

  frontend:
    build: ./packages/frontend
    environment:
      NODE_ENV: ${NODE_ENV}
    depends_on:
      - backend

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
