services:
  backend:
    build: ./services/backend
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - '${BACKEND_PORT}:${BACKEND_PORT}'
    restart: always
    container_name: django-react-backend

  frontend:
    build: ./services/frontend
    env_file:
      - .env
    environment:
      REACT_APP_BACKEND_URL: ${BACKEND_PUBLIC_URL}
      REACT_APP_FRONTEND_URL: ${FRONTEND_PUBLIC_URL}
    ports:
      - '${FRONTEND_PORT}:${FRONTEND_PORT}'
    restart: always
    depends_on:
      - backend
    container_name: django-react-frontend

  db:
    image: postgres:16-alpine
    env_file:
      - .env
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    restart: always
    container_name: django-react-db

  celery-beat-worker:
    build: ./services/backend
    env_file:
      - .env
    links:
      - db
      - mq
      - redis
    restart: always
    container_name: django-react-celery-beat-worker

  celery-data-worker:
    build: ./services/backend
    env_file:
      - .env
    links:
      - db
      - mq
      - redis
    restart: always
    container_name: django-react-celery-data-worker

  redis:
    image: redis:alpine3.17
    env_file:
      - .env
    ports:
      - '${HL_REDIS_PORT}:${HL_REDIS_PORT}'
    restart: always
    container_name: django-react-redis

  mq:
    image: rabbitmq:3.9.26-management-alpine
    ports:
      - '5672:5672'
      # for rabbitmq-ui in browser
      # default user/password is guest/guest
      - '15672:15672'
    restart: always
    container_name: django-react-mq
