version: '3.9'
services:
  backend:
    build: ./services/backend
    depends_on:
      - db
    env_file:
      - .env
    restart: always
    container_name: django-react-backend

  frontend:
    build: ./services/frontend
    env_file:
      - .env
    environment:
      REACT_APP_BACKEND_PORT: ${BACKEND_PORT}
      REACT_APP_PUBLIC_URL: ${PUBLIC_URL}
    restart: always
    depends_on:
      - backend
    container_name: django-react-frontend

  db:
    image: postgres:13-alpine
    env_file:
      - .env
    restart: always
    container_name: django-react-db

  celery-beat-worker:
    build: ./services/backend
    env_file:
      - .env
    links:
      - db
      - mq
      - redis
    restart: always
    container_name: django-react-celery-beat-worker

  celery-data-worker:
    build: ./services/backend
    env_file:
      - .env
    links:
      - db
      - mq
      - redis
    restart: always
    container_name: django-react-celery-data-worker

  redis:
    image: redis:alpine3.17
    ports:
      - '6379:6379'
    restart: always
    container_name: django-react-redis

  mq:
    image: rabbitmq:3.9.26-management-alpine
    ports:
      - '5672:5672'
      # for rabbitmq-ui in browser
      - '15672:15672'
    restart: always
    container_name: django-react-mq
