services:
  backend:
    build:
      context: ./services/backend
      dockerfile: Dockerfile.dev
    volumes:
      - './services/backend:/workspace/app'
    depends_on:
      db:
        condition: service_healthy
    stdin_open: true
    tty: true
    command: /workspace/app/scripts/entrypoint-dev.sh

  frontend:
    build:
      context: ./services/frontend
      dockerfile: Dockerfile.dev
    volumes:
      - './services/frontend:/workspace/app'
      # One-way volume to use node_modules from inside image
      # NOTE:
      #   this can cause docker out of memory issues
      #   this also causes the frontend to be very slow even if you run the frontend locally not in docker
      # - '/workspace/app/node_modules'
    # command: npm run start
    command: /workspace/app/scripts/entrypoint-dev.sh
    # command: sleep infinity

  db:
    volumes:
      - '${PGDBLOCAL}:/var/lib/postgresql/data/'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -p 5432 -q -U ${POSTGRES_USER}']
      interval: 3s
      timeout: 2s
      retries: 7

  celery-beat-worker:
    build:
      context: ./services/backend
      dockerfile: Dockerfile.dev
    volumes:
      - './services/backend:/workspace/app'
    environment:
      MINT_WORKER_TYPE: '${BEAT_MI_WORKER_TYPE}'
      MINT_WORKER_OPTIONS: '${BEAT_MI_WORKER_OPTIONS}'
      CELERY_WORKER_QUEUES: '${BEAT_CELERY_WORKER_QUEUES}'
    command: /workspace/app/scripts/entrypoint-dev.sh

  celery-data-worker:
    build:
      context: ./services/backend
      dockerfile: Dockerfile.dev
    volumes:
      - './services/backend:/workspace/app'
    environment:
      MINT_WORKER_TYPE: '${DATA_MI_WORKER_TYPE}'
      CELERY_WORKER_QUEUES: '${DATA_CELERY_WORKER_QUEUES}'
    command: /workspace/app/scripts/entrypoint-dev.sh

  mq:
    volumes:
      - '/tmp/django-react-mq/data/mq:/var/lib/rabbitmq'
