version: '3.9'
services:
  backend:
    build: ./packages/backend
    depends_on:
      - db
    env_file:
        - .env
    container_name: django-react-backend

  frontend:
    build: ./packages/frontend
    env_file:
        - .env
    environment:
      REACT_APP_BACKEND_PORT: ${BACKEND_PORT}
      REACT_APP_PUBLIC_URL: ${PUBLIC_URL}
    depends_on:
      - backend
    container_name: django-react-frontend

  db:
    image: postgres:13-alpine
    env_file:
      - .env
    container_name: django-react-db
