databases:
  - name: majorziploc_db
    plan: free
    databaseName: api_crud_db_sb9a
    user: majorziploc

services:
  - type: web
    plan: free
    name: api_crud
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "cd ./services/backend && python -m gunicorn -b \"0.0.0.0:${BACKEND_PORT}\" api_crud.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: majorziploc_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
