# Generated by Django 4.2.8 on 2023-12-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledjob',
            name='delete_after_count',
            field=models.IntegerField(null=True),
        ),
    ]
