# Generated by Django 4.2.8 on 2023-12-28 22:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.TextField()),
                ('next_scheduled', models.DateTimeField()),
                ('delay_seconds', models.IntegerField(null=True)),
                ('job_info', models.JSONField(default=dict)),
                ('last_ran', models.DateTimeField(null=True)),
                ('run_count', models.IntegerField(default=0)),
                ('delete_after_count', models.IntegerField(default=1)),
            ],
        ),
    ]
